jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qt6-base-dev extra-cmake-modules lcov libsystemd-dev
      - name: Configure
        run: >-
          cmake -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -B ${{github.workspace}}/build
          --install-prefix ${{github.workspace}}/build/AppDir/usr
          -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON
      - name: Build
        run: cmake --build ${{github.workspace}}/build --verbose --config ${{matrix.build-type}}
      - name: Install
        run: cmake --install ${{github.workspace}}/build --config ${{matrix.build-type}} --verbose
      - name: Package
        run: >-
          cpack -C ${{matrix.build-type}}
          --config ${{github.workspace}}/build/CPackConfig.cmake --verbose
      - name: Create AppImage
        run: |
          wget 'https://github.com/TheAssassin/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage'
          chmod +x linuxdeploy-x86_64.AppImage
          mkdir -p ${{github.workspace}}/build/AppDir/usr/share/icons/hicolor/scalable/apps
          wget 'https://raw.githubusercontent.com/GNOME/adwaita-icon-theme/refs/heads/master/src/fullcolor/application-x-generic.source.svg' -O ${{github.workspace}}/build/AppDir/usr/share/icons/hicolor/scalable/apps/application-x-generic.svg
          cat > ${{github.workspace}}/build/ipv6-config-update.desktop <<EOF
          [Desktop Entry]
          Categories=Utility;
          Exec=ipv6-config-update %u
          Icon=application-x-generic
          Name=ipv6-config-update
          NoDisplay=true
          Type=Application
          Version=1.5
          EOF
          ./linuxdeploy-x86_64.AppImage --appdir ${{github.workspace}}/build/AppDir --output appimage --desktop-file ${{github.workspace}}/build/ipv6-config-update.desktop
          rm ./linuxdeploy-x86_64.AppImage
          mv -v ${{github.workspace}}/*.AppImage ${{github.workspace}}/ipv6-config-update-${{matrix.build-type}}-x86_64.AppImage
      - if: ${{ github.ref_type == 'tag' && matrix.build-type == 'Release' }}
        name: Rename with tag
        run: mv -v ${{github.workspace}}/ipv6-config-update-*.AppImage ${{github.workspace}}/ipv6-config-update-${{github.ref}}-x86_64.AppImage
      - name: 'Upload Artifacts'
        uses: 'actions/upload-artifact@v7'
        with:
          if-no-files-found: error
          name: ipv6-config-update-${{ matrix.build-type }}-Linux
          path: |
            ${{github.workspace}}/ipv6-config-update-*.AppImage
            ${{github.workspace}}/ipv6-config-update-*.zip
      - name: Attest
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: |
            ${{github.workspace}}/ipv6-config-update-*.AppImage
            ${{github.workspace}}/ipv6-config-update-*.zip
      - if: ${{ github.ref_type == 'tag' && matrix.build-type == 'Release' }}
        name: Upload package
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          files: |
            ${{github.workspace}}/build/ipv6-config-update-*.AppImage
    strategy:
      fail-fast: false
      matrix:
        build-type: [Debug, Release]
name: C/C++ CI
'on':
  push:
    branches: [master]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [master]
permissions:
  attestations: write
  contents: write
  id-token: write
